#!/bin/bash
# Create GitHub Issues for Cloudflare Workers AI Multi-Tenant Monorepo

REPO="rainbowkillah/cloudflare-mono-repo"
PROJECT_NUM=12

create_issue() {
    local title="$1"
    local body="$2"
    local labels="$3"
    local milestone="$4"

    echo "Creating: $title"
    ISSUE_URL=$(gh issue create --repo "$REPO" --title "$title" --body "$body" --label "$labels" 2>&1)
    if [[ $ISSUE_URL == https* ]]; then
        # Add to project
        gh project item-add $PROJECT_NUM --owner rainbowkillah --url "$ISSUE_URL" 2>/dev/null
        echo "  -> Added to project"
    else
        echo "  -> Error: $ISSUE_URL"
    fi
}

echo "=== M0: Foundation & Scaffolding ==="
create_issue "[M0] Create monorepo skeleton (apps/packages/tenants/docs/scripts/tests)" "Create the directory structure as defined in plan.md:\n- apps/\n- packages/\n- tenants/\n- docs/\n- scripts/\n- tests/\n\nExit Criteria: All directories exist with appropriate .gitkeep files" "scaffolding,priority:high" "M0"
create_issue "[M0] Set up TypeScript baseline + tsconfig for Workers runtime" "Configure TypeScript for Cloudflare Workers:\n- target: ES2022\n- module: ESNext\n- lib settings appropriate for Workers\n- Strict mode enabled\n\nDecision needed: ESM vs service-worker format" "tooling,priority:high" "M0"
create_issue "[M0] Configure ESLint + Prettier" "Set up linting and formatting:\n- ESLint with TypeScript support\n- Prettier integration\n- Workspace-level configuration" "tooling" "M0"
create_issue "[M0] Set up Vitest test runner" "Configure Vitest for unit testing:\n- Workspace configuration\n- Coverage reporting\n- Watch mode for development" "testing,tooling" "M0"
create_issue "[M0] Create project.json for each apps/* and packages/* target" "Set up Nx project configuration:\n- Each app needs project.json\n- Each package needs project.json\n- Define build/test/lint targets\n\nNote: Codex review identified this as critical - Nx workspace currently has no projects registered" "nx,priority:high" "M0"
create_issue "[M0] Implement tenant resolution middleware (header/hostname priority)" "CRITICAL: Implement tenant resolution:\n1. Check x-tenant-id header first\n2. Fall back to hostname mapping\n3. Optional: JWT claims if auth enabled\n4. REJECT request if tenant cannot be resolved\n5. Attach tenant context to request lifecycle\n\nThis is a HARD REQUIREMENT per plan.md" "core,priority:critical" "M0"
create_issue "[M0] Define tenant.config.json schema + Zod validation" "Create tenant configuration schema:\n- tenantId\n- accountId\n- hostnameMapping\n- ai policy (models, gateway, budgets)\n- vectorize index names\n- kv namespace mappings\n- do class + binding names\n- cors origins\n- featureFlags\n\nUse Zod for runtime validation" "core,priority:high" "M0"
create_issue "[M0] Create core error handling + response envelopes" "Define standard error handling:\n- Error response envelope format\n- HTTP status code mapping\n- Error codes enumeration\n- Stack trace handling (dev vs prod)" "core" "M0"
create_issue "[M0] Set up local dev with wrangler dev" "Configure local development:\n- wrangler dev setup\n- Hot reload configuration\n- Environment variable handling\n- Document wrangler version to use" "dx,tooling" "M0"
create_issue "[M0] Create hello endpoint per tenant + smoke tests" "Implement basic validation:\n- /health endpoint returning tenant info\n- Smoke tests proving tenant resolution\n- Tests for tenant rejection when missing" "testing" "M0"
create_issue "[M0] Define Env typings source of truth (packages/core/src/env.ts)" "Codex review identified need for single source:\n- Create packages/core/src/env.ts\n- Define all binding types\n- Export for use by apps\n- This prevents binding generator drift" "typescript,priority:high" "M0"
create_issue "[M0] Document wrangler version, ESM format decision" "Document runtime decisions:\n- Specific wrangler version to use\n- ESM vs service-worker format choice\n- Local dev approach (wrangler dev vs miniflare)\n- Any Workers runtime constraints" "docs" "M0"

echo ""
echo "=== M1: Streaming Chat + Sessions (DO) + KV Cache ==="
create_issue "[M1] Build /chat endpoint with request schema" "Implement streaming chat endpoint:\n- Request schema: message list, session id, options\n- Input validation with Zod\n- Tenant context required" "api,priority:high" "M1"
create_issue "[M1] Define streaming response contract (SSE vs chunked)" "Technical decision required:\n- SSE vs chunked transfer encoding\n- Event format specification\n- Error handling in stream\n- Connection keep-alive strategy" "api,priority:high" "M1"
create_issue "[M1] Implement Durable Object session store (tenant-scoped)" "Create DO for session management:\n- Session IDs must include tenant\n- Conversation history storage\n- Retention policy implementation" "storage,priority:high" "M1"
create_issue "[M1] Add conversation history with retention policy" "Session data management:\n- Max history length\n- TTL for sessions\n- Cleanup strategy" "storage" "M1"
create_issue "[M1] Implement KV cache layer (tenant-scoped keys)" "KV caching implementation:\n- Key format includes tenant\n- Cache policy rules\n- TTL configuration" "storage" "M1"
create_issue "[M1] Implement DO-based rate limiter (per tenant + per IP/user)" "Rate limiting implementation:\n- Durable Object based\n- Per tenant limits\n- Per IP/user within tenant\n- Configurable thresholds" "security,priority:high" "M1"
create_issue "[M1] Define rate limit keying strategy (tenant+user+ip)" "Codex identified need for concrete strategy:\n- Key composition format\n- Eviction policy\n- Hot-key contention mitigation\n- Unbounded state growth prevention" "security" "M1"
create_issue "[M1] Create streaming behavior tests" "Test streaming functionality:\n- Stream initiation\n- Chunk delivery\n- Stream termination\n- Error handling mid-stream" "testing" "M1"
create_issue "[M1] Create session isolation tests" "Test tenant isolation:\n- Sessions don't leak between tenants\n- Tenant A can't access Tenant B sessions\n- Proper rejection on wrong tenant" "testing" "M1"
create_issue "[M1] Create rate limit enforcement tests" "Test rate limiting:\n- Limits enforced per tenant\n- Limits enforced per user\n- Proper 429 responses\n- Rate limit headers" "testing" "M1"

echo ""
echo "=== M2: AI Gateway Integration + Model Routing ==="
create_issue "[M2] Gateway integration spike - prove connectivity + configuration" "CRITICAL SPIKE:\n- Validate AI Gateway can be used from Workers\n- Prove configuration approach\n- Capture request_id, latency, token usage\n- Document any API constraints\n\nBlocker: Codex notes API details may change" "spike,priority:critical" "M2"
create_issue "[M2] Implement model routing (tenant config chooses models)" "Model selection per tenant:\n- Read from tenant.config.json\n- Support multiple models per tenant\n- Default model fallback" "ai,priority:high" "M2"
create_issue "[M2] Add per-route model override options" "Route-level configuration:\n- /chat may use different model than /search\n- Per-endpoint override in config\n- Validation of allowed models" "ai" "M2"
create_issue "[M2] Implement budget/limits hooks (token limits)" "Cost control:\n- Per-request token limits\n- Per-tenant budgets\n- Integration with rate limiting" "ai,cost" "M2"
create_issue "[M2] Add observability hooks (latency, status, tokens in/out)" "Metrics for AI calls:\n- Latency measurement\n- Response status tracking\n- Token usage (input/output)\n- Model used" "observability,priority:high" "M2"
create_issue "[M2] Document AI Gateway integration in .llm/docs/ai-gateway.md" "Documentation:\n- How routing works\n- Configuration options\n- Troubleshooting guide" "docs" "M2"
create_issue "[M2] Document fallback behavior for API changes" "Risk mitigation:\n- What happens if Gateway API changes\n- Fallback to direct Workers AI\n- Version pinning strategy" "docs" "M2"

echo ""
echo "=== M3: Embeddings + Vectorize + Retrieval + RAG ==="
create_issue "[M3] Implement ingestion pipeline (chunking strategy)" "Document chunking:\n- Chunk size configuration\n- Overlap settings\n- Metadata preservation\n- Tenant isolation in ingestion" "rag,priority:high" "M3"
create_issue "[M3] Implement embedding generation" "Embedding creation:\n- Model selection for embeddings\n- Batch processing\n- Error handling" "rag,priority:high" "M3"
create_issue "[M3] Implement Vectorize upsert with metadata" "Vector storage:\n- Upsert operation\n- Metadata attachment\n- Tenant-scoped namespaces" "storage,priority:high" "M3"
create_issue "[M3] Implement retrieval pipeline (query embedding)" "Query processing:\n- Convert query to embedding\n- Same model as ingestion\n- Caching strategy" "rag,priority:high" "M3"
create_issue "[M3] Implement Vectorize search" "Vector search:\n- Top-k retrieval\n- Score thresholds\n- Metadata filtering" "rag,priority:high" "M3"
create_issue "[M3] Add optional rerank hook interface" "Reranking abstraction:\n- Interface definition\n- Stub implementation\n- Future provider support" "rag" "M3"
create_issue "[M3] Implement RAG response assembly with prompt template" "RAG generation:\n- Context injection\n- Prompt templates\n- Citation formatting" "rag,priority:high" "M3"
create_issue "[M3] Add citations to RAG responses" "Citation support:\n- Source attribution\n- Chunk references\n- Confidence scores" "rag" "M3"
create_issue "[M3] Implement basic safety filters" "Content safety:\n- Input filtering\n- Output filtering\n- Configurable thresholds" "security" "M3"
create_issue "[M3] Ensure Vectorize indexes are tenant-scoped" "CRITICAL: Tenant isolation:\n- Separate indexes per tenant OR\n- Tenant prefix in vectors\n- No cross-tenant search leakage" "storage,priority:critical" "M3"
create_issue "[M3] Create deterministic fixture retrieval tests" "Fixture-based testing:\n- Known documents\n- Expected retrieval results\n- Reproducible tests" "testing" "M3"
create_issue "[M3] Create tenant isolation tests for Vectorize" "Isolation verification:\n- Tenant A vectors not visible to B\n- Cross-tenant search returns empty\n- Proper namespace separation" "testing,priority:high" "M3"
create_issue "[M3] Create metadata integrity tests" "Data integrity:\n- Metadata preserved through pipeline\n- No data loss on upsert\n- Correct retrieval of metadata" "testing" "M3"
create_issue "[M3] Document Vectorize local emulation limitations + staging strategy" "Codex identified blocker:\n- Local Vectorize limitations\n- Staging tenant for integration tests\n- Mocking layer documentation" "docs" "M3"

echo ""
echo "=== M4: AI Search UX Endpoint ==="
create_issue "[M4] Build /search endpoint with output schema" "Search endpoint:\n- Input: query, filters, options\n- Output: structured response\n- Tenant-scoped results" "api,priority:high" "M4"
create_issue "[M4] Define output schema: answer + sources + confidence + follow-ups" "Response structure:\n- Generated answer\n- Source citations\n- Confidence indicators\n- Suggested follow-up queries" "api" "M4"
create_issue "[M4] Implement query rewriting / intent detection" "Query processing:\n- Lightweight intent classification\n- Query expansion/rewriting\n- Spell correction (optional)" "rag" "M4"
create_issue "[M4] Implement caching for common queries (tenant-scoped KV)" "Query caching:\n- Cache key generation\n- TTL configuration\n- Cache invalidation strategy" "storage" "M4"
create_issue "[M4] Add search latency metrics" "Metrics:\n- End-to-end latency\n- Retrieval latency\n- Generation latency" "observability" "M4"
create_issue "[M4] Add cache hit rate metrics" "Cache metrics:\n- Hit/miss ratio\n- Cache size\n- Eviction rate" "observability" "M4"
create_issue "[M4] Create schema validation tests" "Schema testing:\n- Response matches schema\n- Required fields present\n- Type validation" "testing" "M4"
create_issue "[M4] Create caching behavior tests" "Cache testing:\n- Cache hit scenarios\n- Cache miss scenarios\n- TTL expiration" "testing" "M4"

echo ""
echo "=== M5: Tooling / Generative Functions ==="
create_issue "[M5] Define tool schema (JSON schema for name, args, permissions)" "Tool definition:\n- JSON Schema format\n- Required fields\n- Permission model" "api,priority:high" "M5"
create_issue "[M5] Implement tool dispatcher with registry" "Tool execution:\n- Tool registry\n- Dispatch logic\n- Error handling" "core,priority:high" "M5"
create_issue "[M5] Implement validation + auth/permission gating" "Security:\n- Input validation\n- Permission checking\n- Tenant-scoped access" "security,priority:high" "M5"
create_issue "[M5] Implement tool: summarize" "Summarization tool:\n- Text summarization\n- Length options\n- Format options" "tools" "M5"
create_issue "[M5] Implement tool: extract entities" "Entity extraction:\n- Named entities\n- Custom entity types\n- Structured output" "tools" "M5"
create_issue "[M5] Implement tool: classify intent" "Classification tool:\n- Intent categories\n- Confidence scores\n- Multi-label support" "tools" "M5"
create_issue "[M5] Implement tool: tag/chunk docs" "Document processing:\n- Auto-tagging\n- Chunk generation\n- Metadata extraction" "tools" "M5"
create_issue "[M5] Implement tool: ingest docs" "Ingestion tool:\n- Document intake\n- Format conversion\n- Pipeline trigger" "tools" "M5"
create_issue "[M5] Implement audit logging (tool name + args hash + outcome)" "Audit trail:\n- Tool invocation logging\n- Args hashing (no PII)\n- Outcome recording" "observability,security" "M5"
create_issue "[M5] Create permission tests" "Permission testing:\n- Authorized access\n- Unauthorized rejection\n- Cross-tenant denial" "testing" "M5"
create_issue "[M5] Create injection guard tests" "Security testing:\n- Prompt injection attempts\n- Input sanitization\n- Output validation" "testing,security" "M5"
create_issue "[M5] Create tool correctness tests" "Functional testing:\n- Each tool produces expected output\n- Edge cases handled\n- Error scenarios" "testing" "M5"
create_issue "[M5] Document tool contracts" "Documentation:\n- Tool API reference\n- Usage examples\n- Permission requirements" "docs" "M5"

echo ""
echo "=== M6: TTS Contract + Adapter Boundary ==="
create_issue "[M6] Define /tts contract (input: text, voice, format, streaming)" "TTS endpoint contract:\n- Input parameters\n- Voice options\n- Format selection\n- Streaming flag" "api,priority:high" "M6"
create_issue "[M6] Define output contract (audio stream or job id)" "Response format:\n- Streaming audio\n- Job-based async\n- Error responses" "api" "M6"
create_issue "[M6] Implement adapter interface" "Provider abstraction:\n- Common interface\n- Provider registration\n- Fallback handling" "core,priority:high" "M6"
create_issue "[M6] Implement stub with 'not enabled' behavior" "Stub implementation:\n- Clear error message\n- No provider coupling\n- Easy to replace" "core" "M6"
create_issue "[M6] If feasible: implement provider adapter" "Provider integration:\n- If Cloudflare TTS available\n- Or external provider\n- Documented constraints" "integration" "M6"
create_issue "[M6] Create contract tests" "Contract testing:\n- Input validation\n- Output format\n- Error handling" "testing" "M6"
create_issue "[M6] Create stub behavior tests" "Stub testing:\n- Returns appropriate error\n- No crashes\n- Graceful degradation" "testing" "M6"

echo ""
echo "=== M7: Observability, Metrics, QA Gates, Load Tests ==="
create_issue "[M7] Finalize logging schema with required fields" "Logging standard:\n- timestamp, tenant, route, request_id, latency_ms, status\n- Structured JSON format\n- Redaction rules" "observability,priority:high" "M7"
create_issue "[M7] Define correlation IDs and tracing strategy" "Tracing:\n- Request ID propagation\n- Span-like logging\n- Cross-service correlation" "observability,priority:high" "M7"
create_issue "[M7] Implement metrics helpers" "Metrics utilities:\n- Counter helpers\n- Histogram helpers\n- Label management" "observability" "M7"
create_issue "[M7] Implement required metrics" "Core metrics:\n- requests_total\n- errors_total\n- latency_ms_histogram\n- ai_tokens_in_out\n- vectorize_queries_total\n- cache_hit_rate\n- rate_limited_total" "observability" "M7"
create_issue "[M7] Add cost monitoring metrics (token usage)" "Cost tracking:\n- Token usage per tenant\n- Model usage breakdown\n- Budget tracking" "observability,cost" "M7"
create_issue "[M7] Create dashboards/alerts suggestions document" "Operational docs:\n- Dashboard layouts\n- Alert thresholds\n- On-call guidance" "docs" "M7"
create_issue "[M7] Create load test scripts" "Load testing:\n- Chat endpoint load test\n- Search endpoint load test\n- Concurrent tenant simulation" "testing,priority:high" "M7"
create_issue "[M7] Create retrieval quality 'smoke score' regression suite" "Quality testing:\n- Baseline retrieval quality\n- Regression detection\n- Quality metrics" "testing" "M7"
create_issue "[M7] Create streaming stability tests" "Stability testing:\n- Long-running streams\n- Connection handling\n- Error recovery" "testing" "M7"
create_issue "[M7] Set up CI gates (lint, typecheck, unit, integration)" "CI pipeline:\n- Lint gate\n- Type check gate\n- Unit test gate\n- Integration test gate" "ci,priority:high" "M7"
create_issue "[M7] Document failure mode template" "Gemini recommendation:\n- Failure scenario description\n- Impact assessment\n- Detection method\n- Mitigation steps\n- Prevention strategy" "docs" "M7"
create_issue "[M7] Document external dependency failure strategies" "Failure handling:\n- Workers AI unavailable\n- AI Gateway issues\n- Vectorize problems\n- KV/DO failures" "docs" "M7"

echo ""
echo "=== M8: Repeatable Deployment per Tenant + Drift Detection ==="
create_issue "[M8] Create deployment script: deploy one tenant" "Single tenant deploy:\n- Validate config\n- Deploy worker\n- Verify deployment" "deploy,priority:high" "M8"
create_issue "[M8] Create deployment script: deploy all tenants" "Multi-tenant deploy:\n- Iterate tenants\n- Error handling\n- Status reporting" "deploy,priority:high" "M8"
create_issue "[M8] Add environment selection (dev/stage/prod)" "Environment support:\n- Environment configuration\n- Promotion workflow\n- Environment isolation" "deploy" "M8"
create_issue "[M8] Implement config validation (fail fast)" "Validation:\n- Required bindings check\n- Config schema validation\n- Pre-deploy verification" "deploy" "M8"
create_issue "[M8] Implement drift detection (expected vs deployed)" "Drift detection:\n- Compare config to deployed\n- Report differences\n- Optional auto-fix" "deploy" "M8"
create_issue "[M8] Define multi-account credential strategy" "CRITICAL per Codex:\n- wrangler profiles\n- CF_API_TOKEN scoping\n- CI/CD credential management\n- Secret vault integration" "deploy,priority:critical" "M8"
create_issue "[M8] Create deploy rollback runbook" "Rollback docs:\n- Rollback steps\n- Verification checks\n- Communication template" "docs,runbook" "M8"
create_issue "[M8] Create incident response runbook" "Incident docs:\n- Severity classification\n- Response procedures\n- Escalation paths" "docs,runbook" "M8"

echo ""
echo "=== NX-1: Nx Plugin Bootstrap ==="
create_issue "[NX-1] Create Nx plugin package skeleton (packages/nx-cloudflare)" "Plugin setup:\n- Package structure\n- generators.json\n- executors.json\n- Dependencies" "nx,priority:high" "NX-1"
create_issue "[NX-1] Implement init generator" "Init generator:\n- Add baseline workspace config\n- Set up default targets\n- Configure workspace" "nx,priority:high" "NX-1"
create_issue "[NX-1] Add shared utilities: parse tenant config" "Utility functions:\n- JSON parsing\n- Config validation\n- Type definitions" "nx" "NX-1"
create_issue "[NX-1] Add shared utilities: update JSONC (use jsonc-parser)" "JSONC handling:\n- Use jsonc-parser library\n- Preserve comments\n- Format preservation\n\nCodex recommendation: avoid ad-hoc string edits" "nx" "NX-1"
create_issue "[NX-1] Add shared utilities: validate config" "Validation utilities:\n- Schema validation\n- Error reporting\n- Type guards" "nx" "NX-1"
create_issue "[NX-1] Set up plugin testing infrastructure" "Plugin tests:\n- Generator tests\n- Executor tests\n- Snapshot tests" "nx,testing" "NX-1"

echo ""
echo "=== NX-2: Worker Generator ==="
create_issue "[NX-2] Scaffold worker-api template with tenant middleware" "Worker template:\n- Entry point\n- Tenant middleware\n- Basic routing" "nx,priority:high" "NX-2"
create_issue "[NX-2] Add /health endpoint to template" "Health check:\n- Basic health endpoint\n- Tenant info in response\n- Version info" "nx" "NX-2"
create_issue "[NX-2] Add project.json targets for dev/test/deploy" "Nx targets:\n- dev target (wrangler dev)\n- test target (vitest)\n- deploy target (wrangler deploy)" "nx,priority:high" "NX-2"
create_issue "[NX-2] Define executor-to-wrangler mapping" "Executor design:\n- --config tenants/<id>/wrangler.jsonc\n- --cwd mapping\n- Environment flags" "nx" "NX-2"
create_issue "[NX-2] Create worker generator tests" "Generator tests:\n- Output validation\n- Schema compliance\n- Idempotency check" "nx,testing" "NX-2"

echo ""
echo "=== NX-3: Tenant Generator ==="
create_issue "[NX-3] Scaffold tenant folder structure" "Tenant template:\n- tenants/<id>/ directory\n- Required files\n- Optional directories" "nx,priority:high" "NX-3"
create_issue "[NX-3] Generate tenant.config.json template" "Config template:\n- Required fields\n- Default values\n- Documentation comments" "nx" "NX-3"
create_issue "[NX-3] Generate wrangler.jsonc template" "Wrangler config:\n- Binding placeholders\n- Environment config\n- Account mapping" "nx" "NX-3"
create_issue "[NX-3] Add tenant registry file for discoverability" "Registry (optional):\n- List of tenants\n- Metadata\n- Discovery mechanism" "nx" "NX-3"
create_issue "[NX-3] Create tenant generator tests" "Generator tests:\n- Output validation\n- Config validity\n- Integration with worker" "nx,testing" "NX-3"

echo ""
echo "=== NX-4: Bindings + deployAll ==="
create_issue "[NX-4] Implement binding generator (KV/DO/Vectorize/AI)" "Binding generator:\n- Add bindings to wrangler config\n- Support all binding types\n- Validation" "nx,priority:high" "NX-4"
create_issue "[NX-4] Update Env typing from single canonical file" "Type generation:\n- Update packages/core/src/env.ts\n- Consistent types\n- Prevent drift\n\nCodex: single source of truth critical" "nx,priority:high" "NX-4"
create_issue "[NX-4] Add DO class skeleton generation" "DO generation:\n- Class template\n- Binding wiring\n- Type definitions" "nx" "NX-4"
create_issue "[NX-4] Implement deployAll executor" "Deploy executor:\n- Iterate all tenants\n- Execute deploy\n- Report status" "nx,priority:high" "NX-4"
create_issue "[NX-4] Add concurrency policy to deployAll" "Concurrency:\n- Parallel limit\n- Sequential option\n- Resource management" "nx" "NX-4"
create_issue "[NX-4] Add dry-run mode to deployAll" "Dry run:\n- Preview changes\n- No actual deploy\n- Validation only" "nx" "NX-4"
create_issue "[NX-4] Add continue-on-error flag to deployAll" "Error handling:\n- Continue on failure\n- Report all errors\n- Partial success handling" "nx" "NX-4"
create_issue "[NX-4] Create binding generator/executor tests" "Tests:\n- Generator tests\n- Executor tests\n- Integration tests" "nx,testing" "NX-4"

echo ""
echo "=== Review Feedback Issues ==="
create_issue "[Review] Add explicit milestone dependency mapping" "Gemini recommendation:\n- Document cross-milestone dependencies\n- Create dependency graph\n- Update plan.md section" "docs" "Review"
create_issue "[Review] Quantify exit criteria with specific metrics" "Gemini recommendation:\n- P90 latency targets\n- Specific numeric thresholds\n- Measurable success criteria" "docs" "Review"
create_issue "[Review] Define E2E testing layer" "Gemini recommendation:\n- Full user journey tests\n- Cross-component integration\n- Distinct from unit/integration" "testing" "Review"
create_issue "[Review] Add security testing activities" "Gemini recommendation:\n- Static analysis\n- Dynamic analysis\n- Vulnerability scanning" "testing,security" "Review"
create_issue "[Review] Establish performance baselines" "Gemini recommendation:\n- Initial performance metrics\n- Regression thresholds\n- CI integration" "testing" "Review"
create_issue "[Review] Define AuthN/AuthZ strategy" "Codex identified gap:\n- API keys vs JWT vs CF Access\n- Authentication flow\n- Authorization model" "security" "Review"
create_issue "[Review] Pick logging/metrics sink" "Codex identified gap:\n- Workers Analytics Engine vs Logpush vs 3rd party\n- Sampling rules\n- Retention policy" "observability" "Review"

echo ""
echo "Done! All issues created."
